### ISSUE TITLE
Update Google Map API Function

### ISSUE THREAD

**Issue by mmuhamadamirzaidi** [mmuhamadamirzaidi/OxygenToGo#1]
Please update Google Maps API function that compatible with the latest API version

**Comment by victorgvieira** [comment]
Im interested, can i work on it?

**Comment by mmuhamadamirzaidi** [comment]
Sure @victorgvieira. The issues is when you click the button to select the destination and current location, it will return null. 
![Screenshot_20201001_221052_com example oxygentogo](https://user-images.githubusercontent.com/44740963/94820469-1493b600-0433-11eb-9346-9c3883388aac.jpg)
![Screenshot_20201001_221101_com example oxygentogo](https://user-images.githubusercontent.com/44740963/94820477-165d7980-0433-11eb-8e5d-24442750a29b.jpg)
![Screenshot_20201001_221257_com google android gms](https://user-images.githubusercontent.com/44740963/94820685-51f84380-0433-11eb-81ce-ea2d8bc9c04e.jpg)
![Screenshot_20201001_221116_com google android gms](https://user-images.githubusercontent.com/44740963/94820481-178ea680-0433-11eb-8ffa-d80e5dbd89d0.jpg)
![Screenshot_20201001_221418_com example oxygentogo](https://user-images.githubusercontent.com/44740963/94820863-80761e80-0433-11eb-862e-e6a85f3875ef.jpg)
![Screenshot_20201001_221421_com example oxygentogo](https://user-images.githubusercontent.com/44740963/94820877-84a23c00-0433-11eb-8198-43dd65e35730.jpg)

**Comment by victorgvieira** [comment]
@mmuhamadamirzaidi  Did you noticed that the app crashes when it's a fresh installation and the location permission is requested for the first time?

![error_path](https://user-images.githubusercontent.com/15981882/94826641-eb950600-03dd-11eb-855e-3d87daa712d4.png)

**Comment by victorgvieira** [comment]
If you create a new issue with this problem, i could handle it as well

**Comment by mmuhamadamirzaidi** [comment]
Sure. No problem @victorgvieira. Please check issue number 2 at [https://github.com/mmuhamadamirzaidi/OxygenToGo/issues/2](url)
