### ISSUE TITLE
Fix App Crash When Location Permission Allowed

### ISSUE THREAD

**Issue by mmuhamadamirzaidi** [mmuhamadamirzaidi/OxygenToGo#2]
Please help to fix the crash when allowing permission for the location after a fresh installation.

**Comment by victorgvieira** [comment]
Working on it

**Comment by mmuhamadamirzaidi** [comment]
Thanks @victorgvieira

**Comment by mmuhamadamirzaidi** [comment]
Checking

**Comment by mmuhamadamirzaidi** [comment]
Thanks @victorgvieira . Only issue 2 left.
